--- WIFI CONFIGURATION ---
WIFI_SSID = "WIFI_SSID"
WIFI_PASSWORD = "WIFI_PASSWORD"
WIFI_SIGNAL_MODE = wifi.PHYMODE_N

--- DEVICE DATA ---
SERIAL_NUM = 10
FIRMWARE_VERSION = "1.0"

--- MQTT BROKER CONFIGIRATION
MQTT_BROKER_IP = "192.168.1.50"
MQTT_BROKER_PORT = 1883

--- IP CONFIG (Leave blank to use DHCP) ---
ESP8266_IP = ""
ESP8266_NETMASK = ""
ESP8266_GATEWAY = ""

--- CD4051BE CONFIG ---
CD4051BE_PIN_A = 5
CD4051BE_PIN_B = 6
CD4051BE_PIN_C = 7

--- SOIL MOISTURE DATA ---
AFLOWER_MAX_INPUTS = 8
AFLOWER_MAX_MEASURE_REPEAT = 5
